Update theme.toml
I was getting this error using while flowing the hugo quick start, changing to a string fixed it. 
```
Error: failed to read module config for "ananke" in "/Users/theyes/Projects/hugo/demo/themes/ananke/theme.toml": unmarshal failed: Near line 11 (last key parsed 'min_version'): Invalid float value: "0.30.2"
```